name: 🚀 Deploy Thinklet Backend to EC2

on:
  push:
    branches:
      - main  # Trigger only on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/thinklet-backend:latest .

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          cd backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/thinklet-backend:latest

      # Step 5: Deploy to EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🧹 Cleaning old Docker images and containers..."

            # Stop and remove running container if exists
            sudo docker stop thinklet-backend || true
            sudo docker rm thinklet-backend || true

            # Remove old dangling images to free up space
            sudo docker image prune -af || true

            echo "⬇️ Pulling latest image..."
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/thinklet-backend:latest

            echo "🚀 Starting new container..."
            sudo docker run -d --name thinklet-backend \
              --env-file /home/ubuntu/thinklet-backend/.env \
              -p 3000:3000 \
              --restart=always \
              ${{ secrets.DOCKERHUB_USERNAME }}/thinklet-backend:latest

            echo "✅ Deployment complete."
